### ISSUE TITLE
Constant Stream studder when trying to use FTL

### ISSUE THREAD

**Issue by killafuze** [mixer/obs-studio-ftl#100]
https://gist.github.com/a27970f8d9b79085f3727d59d6b22230

This is my log file of my current settings. When recording for myself it works fine but when ever I am on Beam/Mixer the stream constantly studders. Any help would greatly be appreciated!

**Comment by JimmyMac3** [comment]
According to that log file it looks like your running the 32bit version of OBS-FTL. Any reason why your not running the 64bit version?

**Comment by killafuze** [comment]
So here is my log on the 64 bit version, still studdering as it was last night =(

https://gist.github.com/a5d367107ec4e245fa81ca78fd0b0a1f

**Comment by FierySama** [comment]
Does this help with ftl stutter? [https://images-ext-2.discordapp.net/external/j5CPpuxaWRvaRXb5-_JpPEOmSk2oLPkS_km95CVrKT8/https/cdn.discordapp.com/attachments/294228705214070796/327187217367695380/obs64_2017-06-21_13-42-32.png?width=781&height=622](url) this is a fix that may work for you if you have ftl stutter. Bframes is likely the culprit, though I'm not 100% sure if this is the real reason why FTL stutters for you

**Comment by odinti** [comment]
Your link is 404

**Comment by narcogen** [comment]
Correct URL would appear to be:

https://cdn.discordapp.com/attachments/294228705214070796/327187217367695380/obs64_2017-06-21_13-42-32.png?width=781&height=622
