### ISSUE TITLE
MSVCP140.dll missing, 32-bit obs won't start. (32bit capture in 64bit broken too)

### ISSUE THREAD

**Issue by aztectornado** [mixer/obs-studio-ftl#101]
I can't start OBS-FTL in 32-bit mode. On launch it provides an error stating that MSVCP140.dll is missing. Searching for this error I found it was an issue probably caused by a lack of C++ redistributables, but after uninstalling and reinstalling 2013 (the kind OBS vanilla asks for) and 2017 both, the error persists. Reinstalling OBS hasn't worked either.

I'm also experiencing a 0xc000007b error from get-graphics-offsets32.exe on the 64 bit version when I start it up, but as I understand that's something to do with the 32-bit capture not working?

Anyone have any ideas?

**Comment by JimmyMac3** [comment]
MSVCP140.dll is the 2015 C++ Redist not 2013 or 2017 and you need to download and install both the 32bit and 64bit versions no matter which version of OBS you run.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by aztectornado** [comment]
Well that explains a lot. That was the one version of the redists I couldn't get; link was broken on their site. 

This appears to be working now after install. Thank you!
