### ISSUE TITLE
Obs Issue 

### ISSUE THREAD

**Issue by JEStudios** [mixer/obs-studio-ftl#102]
Went to use OBS today and for some reason when I hit the "Start Streaming" I get an error message..

"Starting the output failed. Please check the log for details"

However for the life of me I dont know what is going on ... I have attached the log file any assistance would be appreciated. Not there have been no driver updates lately and the video drivers are up to date.

Thanks for any assistance ;)

[2017-06-26 21-06-11.txt](https://github.com/mixer/obs-studio-ftl/files/1108959/2017-06-26.21-06-11.txt)

**Comment by Maximilian-Reuter** [comment]
Very simple. If you have a look at the Notes section at the Release page you will find:

> Audio sample rate MUST be 48Khz (requires a restart if it was using 44.1khz)

**Comment by JEStudios** [comment]
Hey that fixed the issue thanks
