### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by RbDubs** [mixer/obs-studio-ftl#103]
I'll be the first to admit I'm a 10 watt light bulb when the topic is on tech/computers so this error may be my own doing.  Upon trying to installing I received a obs64.exe - System Error.  "Cannot proceed due to VCRUNTIME140.dll and MSVCP140.dll was not found.   Reinstalling the program may fix the problem."  

Tried reinstalling and downloading files again and same error, even with prior versions of obs-studio-ftl.

Any insight?

**Comment by JimmyMac3** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Download and install both 32 and 64 bit. Problem solved

**Comment by RbDubs** [comment]
Thank you very much!
