### ISSUE TITLE
OBS 19 Alpha Settings

### ISSUE THREAD

**Issue by dnuzum** [mixer/obs-studio-ftl#109]
Just looking for a clarification on the Alpha announce. Says nothing re: suggested settings for FTL streaming. Just wanting to make sure nothing has changed between the forked versions and the intended merge version. Thanks!

**Comment by dorianmuthig** [comment]
In **Settings** ->**Stream**under **Stream Type** you now select **Streaming Services** instead of **Beam/Mixer FTL Service**, under **Service** you select **Mixer.com - FTL** and put in your stream key in the input field. Everything else will work as before, or at least, it should.
