### ISSUE TITLE
NVENC Encoder Low Latency Settings

### ISSUE THREAD

**Issue by ibigfire** [mixer/obs-studio-ftl#30]
On the release page you list the "###Lowest Latency Settings####" which is great!  But you only have them listed for an x264 encoder.  Any chance you could list them for NVENC as well?

**Comment by JimmyMac3** [comment]
I wasn't aware that FTL worked with NVENC  I know it doesn't with AMD Video Coding Engine. Crashes every time.

**Comment by Maximilian-Reuter** [comment]
It does, though you'll have to set the bframe count to 0 or else i get a severely degraded stream

**Comment by sslivins** [comment]
ftl is agnostic to the type of encoder and does work with NVENC, in addition to Intels QuickSync, and should work with AMD's VCE (however i have not personally tried it, if you had additional details on your crash @JimmyMac3 i can look into it).  Regarding your question @ibigfire NVENC has significantly higher delay (about 1 second), there are no settings that can decrease this which is why i do not include suggested settings for NVENC.

**Comment by ibigfire** [comment]
Ah.  Hm.  Any idea how I can get it as low as possible?  I was using Tachyon with fairly low delay, yeah, about 1 second (give or take) like you say.  And now it's jumped up to about 30+ now that I've switched to OBS-Studio-FTL.  Tachyon was pretty minimal in what it let me change when using FTL so I'm not sure how to get it to be similar.

**Comment by sslivins** [comment]
30+ seconds is not normal, can you attach your logs (when you noticed the delay is high go to logs->upload current log) and paste the link here

**Comment by JimmyMac3** [comment]
ibigfire - In SETTINGS > STREAM is STREAM TYPE set to Beam FTL Service ?   Sounds like your not using the FTL Protocol

**Comment by ibigfire** [comment]
It is set to FTL.  I went ahead and uploaded a log, it's about 10 seconds or so of delay currently, but it gets more delayed over time.

**Comment by Maximilian-Reuter** [comment]
@ibigfire if you want people to actually read the log you will have to post the link to it.

**Comment by ibigfire** [comment]
Whoops.  >_<  Good call.  https://gist.github.com/anonymous/aa5a7cddeb8d94e2028493db82711b27

**Comment by sslivins** [comment]
definitely using the ftl protocol in the logs provided.  oddly i dont see the tell tale signs of delay building up.  was it happening is this particular log?  my suggestion would be to reproduce the issue again and before shutting down or stopping the stream hit logs->upload current log and past the link again here.  also ensure you're not on flash on the browser end, you should see the blue ftl logo in the corner of the stream

**Comment by ibigfire** [comment]
Okay.  Sorry for they delay, been a busy week.  Here's a new log:  https://gist.github.com/fbf8e629ad09696ca8bdf1ec73915fa1

This log is without shutting down first or stopping the stream.  It does have the blue ftl logo in the corner of the stream, so it's definitely using ftl.  What is happening is that every so often my stream will stutter slightly, and everytime it stutters it gets more and more delayed.  Using a lower bitrate does not solve the issue.  Lowering my graphics settings in the game also does not seem to solve it either, unfortunately.
