### ISSUE TITLE
Many games don't seem to be supported via Game Capture

### ISSUE THREAD

**Issue by Dementei** [mixer/obs-studio-ftl#41]
I have the latest OBS Studio FTL version and I can't seem to get Game Capture to work properly. Using normal OBS, it works fine, it captures any game as it should. The game I am testing it out with is Arma 3, and I have used it with and without the anti-cheat compatibility hooking as well as both x32 and x64 versions of OBS Studio FTL. Have any suggestions? (I would use Window Capture or Display but both aren't optimal for performance)

**Comment by Maximilian-Reuter** [comment]
could you post one of your logs where that happened ? It's under Help->Log Files->Upload Current Logfile
Then post it here. Otherwise it's almost impossible to diagnose your problem.

**Comment by Dementei** [comment]
Ah right, here you go.

> 11:45:16.296: CPU Name: AMD FX(tm)-8350 Eight-Core Processor           
11:45:16.296: CPU Speed: 4621MHz
11:45:16.296: Physical Cores: 4, Logical Cores: 8
11:45:16.296: Physical Memory: 16348MB Total, 11210MB Free
11:45:16.296: Windows Version: 6.3 Build 9600 (revision: 17056; 64-bit)
11:45:16.296: Running as administrator: false
11:45:16.296: Aero is Enabled (Aero is always on for windows 8 and above)
11:45:16.296: Portable mode: false
11:45:16.306: OBS 0.16.6-ftl.18 (64bit, windows)
11:45:16.306: ---------------------------------
11:45:16.307: ---------------------------------
11:45:16.307: audio settings reset:
11:45:16.307: 	samples per sec: 48000
11:45:16.307: 	speakers:        2
11:45:16.308: ---------------------------------
11:45:16.308: Initializing D3D11..
11:45:16.308: Available Video Adapters: 
11:45:16.308: 	Adapter 1: NVIDIA GeForce GTX 770
11:45:16.308: 	  Dedicated VRAM: 2052853760
11:45:16.308: 	  Shared VRAM:    4276418560
11:45:16.308: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
11:45:16.310: Loading up D3D11 on adapter NVIDIA GeForce GTX 770 (0)
11:45:16.331: D3D11 loaded sucessfully, feature level used: 45056
11:45:16.858: ---------------------------------
11:45:16.858: video settings reset:
11:45:16.858: 	base resolution:   1920x1080
11:45:16.858: 	output resolution: 1280x720
11:45:16.858: 	downscale filter:  Lanczos
11:45:16.858: 	fps:               60/1
11:45:16.858: 	format:            NV12
11:45:16.860: ---------------------------------
11:45:16.867: [CoreAudio encoder]: Adding CoreAudio AAC encoder
11:45:16.874: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
11:45:16.876: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
11:45:16.876: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libftl.dll' not found, loading of module failed
11:45:16.878: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
11:45:16.878: Failed to load 'en-US' text for module: 'obs-browser.dll'
11:45:16.879: NVENC supported
11:45:16.939: No blackmagic support
11:45:16.943: ---------------------------------
11:45:16.943:   Loaded Modules:
11:45:16.943:     win-wasapi.dll
11:45:16.943:     win-mf.dll
11:45:16.943:     win-dshow.dll
11:45:16.943:     win-decklink.dll
11:45:16.943:     win-capture.dll
11:45:16.943:     text-freetype2.dll
11:45:16.943:     rtmp-services.dll
11:45:16.943:     obs-x264.dll
11:45:16.943:     obs-transitions.dll
11:45:16.943:     obs-text.dll
11:45:16.943:     obs-qsv11.dll
11:45:16.943:     obs-outputs.dll
11:45:16.943:     obs-filters.dll
11:45:16.943:     obs-ffmpeg.dll
11:45:16.943:     obs-browser.dll
11:45:16.943:     image-source.dll
11:45:16.943:     ftl-services.dll
11:45:16.943:     frontend-tools.dll
11:45:16.943:     coreaudio-encoder.dll
11:45:16.943: ==== Startup complete ===============================================
11:45:16.944: [ftl stream: '(null)'] ftl_stream_create
11:45:16.944: 
11:45:16.945: All scene data cleared
11:45:16.945: ------------------------------------------------
11:45:16.968: WASAPI: Device 'Realtek HD Audio 2nd output (Realtek High Definition Audio)' initialized
11:45:16.982: WASAPI: Device 'Microphone (HD Webcam C270)' initialized
11:45:16.982: source 'Mic/Aux' enabled push-to-talk
11:45:17.018: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds
11:45:17.124: Switched to scene 'Game'
11:45:17.124: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
11:45:17.124: [game-capture: 'Game Capture'] could not open process: arma3.exe
11:45:17.124: ------------------------------------------------
11:45:17.124: Loaded scenes:
11:45:17.124: - scene 'Game':
11:45:17.124:     - source: 'Game Capture' (game_capture)
11:45:17.124: ------------------------------------------------
11:45:17.274: Update check: last known remote version is 0.16.6
11:45:19.127: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
11:45:19.127: [game-capture: 'Game Capture'] could not open process: arma3.exe
11:45:21.143: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
11:45:21.143: [game-capture: 'Game Capture'] could not open process: arma3.exe
11:45:23.160: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
11:45:23.160: [game-capture: 'Game Capture'] could not open process: arma3.exe

>

**Comment by Maximilian-Reuter** [comment]
the error means that obs cant access the process, could you try starting obs as administrator ?

**Comment by Dementei** [comment]
Okay here is running it as administrator, with and without the anti-cheat compatibility hook.

> 17:23:13.136: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
17:23:13.137: [game-capture: 'Game Capture'] using helper (compatibility hook)
17:23:13.137: ------------------------------------------------
17:23:13.137: Loaded scenes:
17:23:13.137: - scene 'Game':
17:23:13.137:     - source: 'Game Capture' (game_capture)
17:23:13.137: ------------------------------------------------
17:23:13.357: Update check: last known remote version is 0.16.6
17:23:17.162: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
17:23:17.162: [game-capture: 'Game Capture'] using helper (compatibility hook)
17:23:21.262: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
17:23:21.263: [game-capture: 'Game Capture'] using helper (compatibility hook)
17:23:22.874: adding 192 milliseconds of audio buffering, total audio buffering is now 234 milliseconds
17:23:25.379: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
17:23:25.379: [game-capture: 'Game Capture'] using helper (compatibility hook)
17:23:29.412: [game-capture: 'Game Capture'] attempting to hook process: arma3.exe
17:23:29.412: [game-capture: 'Game Capture'] using helper (direct hook)
17:23:29.445: [game-capture: 'Game Capture'] inject process failed: -4
17:23:35.699: adding 42 milliseconds of audio buffering, total audio buffering is now 277 milliseconds

>

**Comment by sslivins** [comment]
im going to experiment with a few things, i dont know exactly why this is the case either
