### ISSUE TITLE
H1Z1 Issue Blocking OBS Studio FTL

### ISSUE THREAD

**Issue by rinrinrinoa** [mixer/obs-studio-ftl#42]
So I was trying to stream H1Z1: King of the Kill and for some reason it would not show as Game Capture. When I change to regular OBS Studio without FTL it would game capture perfectly. I did get a pop up from the BattlEye Launcher that they 16:53:53: [INFO] Blocked loading of file: "E:\data\obs-plugins\win-capture\graphics-hook64.dll". Is there something that could be done? Please let me know if you need any further information.

**Comment by sslivins** [comment]
could be permissions...try running obs-ftl as an administrator

**Comment by rinrinrinoa** [comment]
I tried as an administrator and it didn't work

**Comment by CAProjects** [comment]
I have this same exact issue with Star Wars Battlefront and running as admin does not work and i have tried everthing possible. not had any issue with other games

**Comment by SingingTurnip** [comment]
Just tried H1Z1 king of the kill and OBS 17.0.0-ftl.28 will not open it because of graphics-hook64.dll being blocked also, I am on Window 10.

**Comment by Maximilian-Reuter** [comment]
see #56
