### ISSUE TITLE
Noise Supression Filter

### ISSUE THREAD

**Issue by M00CH1E** [mixer/obs-studio-ftl#45]
I just noticed that in the Microphone audio settings there is no Noise Supression Filter like there is in the Normal OBS Studio. 

The data file for the supression filter is there in the code section for OBS -FTL? 

Is there a reason why this is no active in the program?  this really helps with removing a lot of the background noise on top of the noise gate.

**Comment by Maximilian-Reuter** [comment]
If you take a look at the Cmake file in that folder, it is looking for a Libspeexdsp which I guess is currently not being used in the build scripts. @sslivins would have to compile that from source as I didn't find any binaries.

**Comment by tobiasschulz** [comment]
libspeexdsp is included in the pre-built dependencies of the official obs studio:

https://obsproject.com/downloads/dependencies2015.zip (https://github.com/jp9000/obs-studio/wiki/Install-Instructions#windows)

**Comment by M00CH1E** [comment]
thanks for the replies guys. I dont suppose either of you have any ideas about my previous issue regarding Browser_source plugin stopping running all the time until refreshed.

**Comment by Maximilian-Reuter** [comment]
Not of the top of my head... Did you try reproducing this with the upstream OBS ? Could be a bug from there as there isn't really that much difference between this project and OBS

**Comment by M00CH1E** [comment]
It seems to work fine with the normal OBS Studio. I dont know of anyone else having the issue. it can work fine for ages and then it can disappear every few seconds in the FTL version

**Comment by pnkllr** [comment]
Any word on when noise suppression will be added into the ftl version?
