### ISSUE TITLE
Crash when starting stream on Linux

### ISSUE THREAD

**Issue by jacobmischka** [mixer/obs-studio-ftl#50]
I'm not sure how supported this is on Linux yet, but I'm getting an instant crash when trying to stream with FTL after building from source.

Regular RTMP streaming works fine.

Console out: https://gist.github.com/jacobmischka/8ff7c5dea0eac5d591fe29f071f9b33b

Thank you!

**Comment by MRebhan** [comment]
This happens for me too.

**Comment by jacobmischka** [comment]
Is this closed because it's fixed, or because this will not be supported? Either way no problem, just wondering. Thanks!

**Comment by MRebhan** [comment]
It works for me now, and has been for some time.

**Comment by QuinnDamerell-MS** [comment]
We have merged with official OBS, so that should fix the issue. Go check it out!
