### ISSUE TITLE
Strange issue when first launching

### ISSUE THREAD

**Issue by Saiasanc** [mixer/obs-studio-ftl#51]
So I am not quite sure how to explain this properly. But here goes anyways:

Every once in awhile when I launch I get the usual Windows UAC window asking if I want to allow it to make changes to my computer.  But after clicking Yes, nothing seems to happen. No OBS window or anything comes up.  But if I open task manager, there is "obs64.exe" using ~34%-ish of my CPU.  I have to end task on it as well as "cef-bootstrap.exe" manually from task manager and then re-launch to get the actual interface to come up.  It doesn't happen every single time.  But I would say a good 30%-40% of the time.

Is this something I am doing wrong?  Or is it an actual bug within the program?  FYI that I have the exact same problem with regular OBS Studio. So it isn't just with the FTL version.  Oh and checking the log files shows nothing out of the ordinary. So it isn't like it is silently crashing or anything.

Oh and to piggyback a similar issue. The same ~30%-40% of the time when I AM able to get the interface up, after finishing stream and exiting OBS, I have to go into task manager and manually end task on the same "obs64.exe" and "cef-bootstrapper.exe" processes to free up CPU usage. Exiting does not always seem to properly exit the processes it uses.  This happens whether I use the close button (X in upper right of the window) or the "Exit" button in the lower right of the window.  Just as with the other issue above, this happens with regular OBS as well as OBS FTL.  And the logs do not ever indicate a possible crash.

I hope I explained that well enough that everyone can understand. Let me know if any additional information is needed.

--Sai

**Comment by Maximilian-Reuter** [comment]
Question: IF this, as you say yourself, happens with the regular OBS as well, why are you posting it here?
Not trying to be rude or anything just wondering. This is an issue tracker for issues with the FTL OBS, so this doesn't really seem to fit here.

Just in case you don't know where to direct this: https://github.com/jp9000/obs-studio is the repository for the regular OBS. And from what I can gather there seems to already exist a bugreport kinda describing that first behaviour: https://obsproject.com/mantis/view.php?id=749

--Maximilian

**Comment by TweakGames** [comment]
This is happening to me. It does it with normal obs or FTL.  I have just learned to start it, kill it in task manager and start it up again.  Not sure why.

**Comment by ProsperCraft** [comment]
I am having the same problem, I have not tried OBS studio without FTL.

**Comment by Maximilian-Reuter** [comment]
According to the bugtracker this issue should be resolved in 17.0.1 If nobody objects I'd say this issue can be closed.
