### ISSUE TITLE
Latest build (17.0.0-ftl.24) unable to use Game Capture for ARMA 3 - Works in main OBS build 17

### ISSUE THREAD

**Issue by R0ot2U** [mixer/obs-studio-ftl#53]
Not picking up ARMA games when using game capture. Possibly due to the anti-hook cheat compatibility mode as usually ARMA games don't work in regular OBS with that unchecked. 

Workarounds:
Use window capture. 
As mentioned in [#57](https://github.com/WatchBeam/obs-studio-ftl/issues/57) you can copy the graphics-hook32.dlls and graphics-hook64.dll from the original obs at "data\obs-plugins\win-capture" into the ftl obs

**Comment by mmetully** [comment]
Yeah, looks like it works in main page OBS but not obs-studio-ftl

**Comment by Maximilian-Reuter** [comment]
as posted in #57 you could try copying the graphics-hook.dlls from the original obs at "data\obs-plugins\win-capture" into the ftl obs

**Comment by R0ot2U** [comment]
That worked like a charm @Maximilian-Reuter

**Comment by Gol-D-Ace** [comment]
The original OBS is using binary signing.
BattlEye checks the signature of the DLLs and auto allows it.

If beam wants to do this properly they will need to get a certificate, sign the stuff and work/talk with BattlEye.
