### ISSUE TITLE
paladins

### ISSUE THREAD

**Issue by ProManicx** [mixer/obs-studio-ftl#56]
Hellos, ok I have try everything on paladins to work as game capture, but is not working?! any ideas?!  

https://gist.github.com/64a6666911c42106eb2dba7767f79681

**Comment by Maximilian-Reuter** [comment]
is this still happening with the newest version ?

**Comment by ProManicx** [comment]
yes, is not capture the game, have the new version.

**Comment by Maximilian-Reuter** [comment]
does it work with regular OBS ?

**Comment by ProManicx** [comment]
yes works fine

https://gist.github.com/5cdcf5baa79f24c9d898cad3a29f94bb

**Comment by Maximilian-Reuter** [comment]
after further investigation this seems to happen because @sslivins doesn't sign "graphics-hook32/64.dll" or maybe even paladins and others only allow hooks with the OBS certificate...

Anyways simple workaround is, to copy the "graphics-hook32.dll" and "graphics-hook64.dll" from "data\obs-plugins\win-capture" from the original obs into the obs ftl folder at the same location.

**Comment by ProManicx** [comment]
working fine for far, thanks! ;)

**Comment by Barduke** [comment]
Same problem and solution in For Honor.

**Comment by Matlock42** [comment]
Battleye anti-cheat has same problem/solution.

**Comment by decaymarksman** [comment]
so i have a problem now it says hook not loading retrying on the log file.

**Comment by Lewatoto** [comment]
i have the same problem on  OBS 20.1.1 https://gist.github.com/Lewatoto/0f0e9110ca711d485a557a120ebb3c38

error:
`[game-capture: 'Paladins'] hook not loaded yet, retrying..`

**Comment by QuinnDamerell-MS** [comment]
@Lewatoto have you tried the official build of OBS? It now supports FTL out of the box!

**Comment by narcogen** [comment]
That IS the official build. @Lewatoto you should post issues with OBS against their project, not this one.

Try the official Windows support forum:  

https://obsproject.com/forum/list/windows-support.32/

**Comment by Lewatoto** [comment]
ok, sorry i had many tabs open so i posted on the first tab that i see the paladins topic
