### ISSUE TITLE
libVLC

### ISSUE THREAD

**Issue by nicknick923** [mixer/obs-studio-ftl#60]
Is there any way you can re-add the libVLC functionality?
It was added to OBS Studio in release 0.15.0 (https://github.com/jp9000/obs-studio/releases/tag/0.15.0)

**Comment by Scrxtchy** [comment]
https://github.com/WatchBeam/obs-studio-ftl/tree/ftl/plugins/vlc-video

it's there, but the application needs the correct flags to build it with the functionality, Stefan has said that these aren't obvious to him and if anyone knows or has information to contact him with it

**Comment by MatthewM** [comment]
Actually had been wondering about this myself. From what I did digging on the OBS project's forums.. it seems you need [libvlc](https://wiki.videolan.org/LibVLC/#Compiling) to compile it.

Forum topic on this is [here](https://obsproject.com/forum/threads/compilation-for-ubuntu-enable-vlc-stream-support.62768/).

**Comment by Gol-D-Ace** [comment]
What you do is simple.
Clone the vlc repo with git.
Set VLCPath to the just cloned git repo and it will build (under windows).

**Comment by Scrxtchy** [comment]
lol, a lot of these being closed since the upstream
Good work to everyone on the project
