### ISSUE TITLE
Build error on Mac OS X 10.12.3

### ISSUE THREAD

**Issue by UnnDunn** [mixer/obs-studio-ftl#63]
I am trying to build OBS Studio FTL, but I am getting this error when running `./build_script/build_osx`:

    /obs-studio-ftl/plugins/libftl/ftl-sdk/libftl/ftl_helpers.c:267:8: error: 
          implicit declaration of function 'isdigit' is invalid in C99
          [-Werror,-Wimplicit-function-declaration]
                    if (!isdigit(ftl->ingest_hostname[0])) {
                         ^

This is on commit ca90af8.

**Comment by HelloWorldCN** [comment]
modify cmakefilelists.txt

set(CMAKE_C_FLAGS "-Wall -Wextra -Wno-unused-function -Werror-implicit-function-declaration -Wno-error -Wno-implicit-function-declaration -Wno-missing-braces -Wno-missing-field-initializers ${CMAKE_C_FLAGS} -std=gnu99 -fno-strict-aliasing")

**Comment by QuinnDamerell** [comment]
If this fix works and is of good quality please consider submitting a pull request!

**Comment by Maximilian-Reuter** [comment]
seems like [this](https://github.com/WatchBeam/ftl-sdk/issues/47) might be a better solution

**Comment by SwooshyCueb** [comment]
This issue was fixed with commit `1fdf1b5e8cfd56ab6a4504d173a1fbed5eb0cf34` in the `ftl-sdk` repo.
(I think. It fixed the issue for Linux with gcc anyway.)

Should you need to compile from sources older than this commit, just add `#include <ctype.h>` to `plugins/libftl/ftl-sdk/libftl/ftl_helpers.c`
