### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by rinrinrinoa** [mixer/obs-studio-ftl#64]
I just updated to OBS Studio 18.0.1 FTL.9 and when I open OBS 64 and 32-bit I get a system error "The program can't start because widevinecdm.dll is missing from your computer. Try reinstalling the program to fix this problem."

I did reinstall the program and the error is still popping up.

**Comment by QuinnDamerell** [comment]
If you install normal OBS does it run?

**Comment by rinrinrinoa** [comment]
I just installed normal OBS Studios and it opens fine WITHOUT the system error

**Comment by QuinnDamerell** [comment]
And I assume FTL-OBS still doesn't work?

**Comment by rinrinrinoa** [comment]
Correct.

**Comment by QuinnDamerell-MS** [comment]
@rinrinrinoa when you run normal OBS, do you have any web browsers in your scenes?

**Comment by rinrinrinoa** [comment]
@QuinnDamerell-MS Yes on normal OBS I have web browsers in the scenes loots, pixelchat, and Streamjar
