### ISSUE TITLE
18.0.0 with FTL 0.9.0, no audio from media source when monitoring device != default

### ISSUE THREAD

**Issue by nerdism** [mixer/obs-studio-ftl#65]
Working in v18 non ftl, the title says most of whats whats wrong, 
Steps to reproduce: 
1. Settings > Advanced > Audio Monitoring Device, set to a non default audio device.
2. Add media source with audio.
3. Stream on ftl & play media source. 

If you need any more info from my end let me know.

**Comment by digitronics** [comment]
Did some more testing. Seems it works some of the time. Changing devices to be monitored seem to bug out too. Not sure if ill be reproducible via the instructions above, to get it ti break I had to do run the scene a few times and it would stop out-putting the audio.
