### ISSUE TITLE
widevinecdm.dll missing

### ISSUE THREAD

**Issue by EnderAtreides** [mixer/obs-studio-ftl#68]
(Low priority.)

I've tried reinstalling 3x, deleting AppData files, manually updating widevinecdm via [the official site](http://www.widevine.com/download/videooptimizer), all to no avail. I can still use OBS, it just throws the error _every time I start it._ Vanilla (non-FTL) OBS doesn't.

Specifically:

**obs64.exe - System Error**
The program can't start because widevinecdm.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by VallenFrostweaver** [comment]
As above but here is a screen shot:
![temp1](https://cloud.githubusercontent.com/assets/13642054/23653273/df147654-0323-11e7-99b8-5cda4155df02.png)

**Comment by R0ot2U** [comment]
Same issue here https://github.com/WatchBeam/obs-studio-ftl/issues/64

**Comment by QuinnDamerell-MS** [comment]
@VallenFrostweaver when you run normal OBS, do you have a web browser in any of your scenes?
