### ISSUE TITLE
OBS 18.0.1-ftl.0.9.4 - Cant Start Missing 'widevinecdm.dll'

### ISSUE THREAD

**Issue by KirscheBuster** [mixer/obs-studio-ftl#77]
I cannot launch OBS 18.0.1-ftl.0.9.4. I get 'The program can't start because the widevinecdm.dll is missing from your computer. Try reinstalling the program to fix this problem.' I did not have this issue with 17.0.2 with FTL.32

Event Log:
Faulting application name: obs64.exe, version: 0.0.0.0, time stamp: 0x58d29914
Faulting module name: obs64.exe, version: 0.0.0.0, time stamp: 0x58d29914
Exception code: 0xc0000005
Fault offset: 0x000000000000bc7f
Faulting process id: 0x3884
Faulting application start time: 0x01d2a4dd7a6da699
Faulting application path: C:\Program Files (x86)\OBS Studio - FTL\bin\64bit\obs64.exe
Faulting module path: C:\Program Files (x86)\OBS Studio - FTL\bin\64bit\obs64.exe
Report Id: ed92ffa5-10d0-11e7-82c3-ecf4bb2bfdea
Faulting package full name: 
Faulting package-relative application ID: 

System Information:
OS Name	Microsoft Windows 8.1 Enterprise
Version	6.3.9600 Build 9600
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	
System Manufacturer	Dell Inc.
System Model	Latitude E6440
System Type	x64-based PC
System SKU	Latitude E6440
Processor	Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz, 2901 Mhz, 2 Core(s), 4 Logical Processor(s)

**Comment by KirscheBuster** [comment]
Installing the Widevine CDM plugin for IE and Chrome did not fix this problem. I can confirm the path to the DLL and the DLL version.

- C:\Users\AhhYiss\AppData\Local\Steam\widevine\widevinecdm.dll

- widevinecdm.dll, v1.4.8.903, 5.52 MB, 7/15/2016, 6:03pm

manifest.json

{
    "arch": "ia32",
    "description": "Widevine Content Decryption Module",
    "manifest_version": 2,
    "name": "WidevineCdm",
    "offline_enabled": false,
    "os": "win",
    "version": "1.4.8.903",
    "x-cdm-codecs": "vp8,vp9.0,avc1",
    "x-cdm-host-versions": "8",
    "x-cdm-interface-versions": "8",
    "x-cdm-module-versions": "4"
}

https://tools.google.com/dlpage/widevine

**Comment by QuinnDamerell-MS** [comment]
Hey, can you run normal OBS? If so, do you have a web browser in any of your scenes?

**Comment by KirscheBuster** [comment]
Quinn, I can run normal OBS. I do have web sources enabled using stream jar and loots.

**Comment by QuinnDamerell-MS** [comment]
@KirscheBuster do you have chrome installed?

**Comment by KirscheBuster** [comment]
Quinn, yessir I do.

**Comment by RjBass3** [comment]
I am having this same problem.  No fix yet?

**Comment by RjBass3** [comment]
Actually I solved it.  I went to this site: https://www.dll-files.com/widevinecdm.dll.html and downloaded the widevinecdm.dll file.  I then dropped it in the bin/32bit folder.  From there it worked.
