### ISSUE TITLE
5+ Second Video delay when streaming. 

### ISSUE THREAD

**Issue by InfernumBeam** [mixer/obs-studio-ftl#78]
Okay. So, Streaming on OBS FTL 18.0.1 FTL 0.9.4, there is a very odd delay between my voice and system sounds and the Video that is put through. I have tried to restart OBS, Restart the PC and even re-install OBS. None of these options work. I can, however go to regular RTMP OBS and have no de-sync issues at all.

There is no delay set on anything in the settings. and when watching the sound bars and myself in the preview window everything seems to sync up just fine....

**Comment by Maximilian-Reuter** [comment]
As always please provide your log from one of the sessions where the delay appeared.

**Comment by InfernumBeam** [comment]
Where can I find the FTL logs? I can get to the regular OBS logs, but am having troubles locating the ones for FTL

**Comment by InfernumBeam** [comment]
21:25:18.131: CPU Name: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
21:25:18.131: CPU Speed: 3408MHz
21:25:18.131: Physical Cores: 4, Logical Cores: 8
21:25:18.131: Physical Memory: 16287MB Total, 10888MB Free
21:25:18.131: Windows Version: 10.0 Build 14393 (revision: 953; 64-bit)
21:25:18.131: Running as administrator: false
21:25:18.131: Aero is Enabled (Aero is always on for windows 8 and above)
21:25:18.131: Portable mode: false
21:25:18.212: OBS 18.0.1-ftl.0.9.4 (64bit, windows)
21:25:18.212: ---------------------------------
21:25:18.213: ---------------------------------
21:25:18.213: audio settings reset:
21:25:18.213: 	samples per sec: 48000
21:25:18.213: 	speakers:        2
21:25:18.214: ---------------------------------
21:25:18.214: Initializing D3D11..
21:25:18.214: Available Video Adapters: 
21:25:18.215: 	Adapter 1: AMD Radeon (TM) R9 360
21:25:18.215: 	  Dedicated VRAM: 2123870208
21:25:18.215: 	  Shared VRAM:    4244160512
21:25:18.215: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
21:25:18.215: 	Adapter 2: Intel(R) HD Graphics 530
21:25:18.215: 	  Dedicated VRAM: 134217728
21:25:18.215: 	  Shared VRAM:    4244160512
21:25:18.215: 	  output 1: pos={1920, 0}, size={1024, 768}, attached=true
21:25:18.216: Loading up D3D11 on adapter AMD Radeon (TM) R9 360 (0)
21:25:18.225: D3D11 loaded sucessfully, feature level used: 45056
21:25:18.847: ---------------------------------
21:25:18.847: video settings reset:
21:25:18.847: 	base resolution:   1920x1080
21:25:18.847: 	output resolution: 1280x720
21:25:18.847: 	downscale filter:  Lanczos
21:25:18.847: 	fps:               30/1
21:25:18.847: 	format:            NV12
21:25:18.848: Audio monitoring device:
21:25:18.848: 	name: Default
21:25:18.848: 	id: default
21:25:18.848: ---------------------------------
21:25:18.849: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
21:25:18.850: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
21:25:18.852: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/ftl.dll' not found, loading of module failed
21:25:18.857: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
21:25:18.858: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
21:25:18.859: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
21:25:18.859: Failed to load 'en-US' text for module: 'obs-browser.dll'
21:25:18.859: [browser_source: 'Version: 1.29.0']
21:25:18.860: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
21:25:18.860:  (126)
21:25:18.870: LoadLibrary failed for '../../obs-plugins/64bit/widevinecdmadapter.dll': The specified module could not be found.
21:25:18.870:  (126)
21:25:18.870: Module '../../obs-plugins/64bit/widevinecdmadapter.dll' not found
21:25:18.872: No blackmagic support
21:25:19.068: ---------------------------------
21:25:19.068:   Loaded Modules:
21:25:19.068:     win-wasapi.dll
21:25:19.068:     win-mf.dll
21:25:19.068:     win-dshow.dll
21:25:19.068:     win-decklink.dll
21:25:19.068:     win-capture.dll
21:25:19.068:     text-freetype2.dll
21:25:19.068:     rtmp-services.dll
21:25:19.068:     obs-x264.dll
21:25:19.068:     obs-vst.dll
21:25:19.068:     obs-transitions.dll
21:25:19.068:     obs-text.dll
21:25:19.068:     obs-qsv11.dll
21:25:19.068:     obs-outputs.dll
21:25:19.068:     obs-filters.dll
21:25:19.068:     obs-ffmpeg.dll
21:25:19.068:     obs-browser.dll
21:25:19.068:     image-source.dll
21:25:19.068:     ftl-services.dll
21:25:19.068:     frontend-tools.dll
21:25:19.068:     coreaudio-encoder.dll
21:25:19.068: ==== Startup complete ===============================================
21:25:19.068: [ftl stream: '(null)'] ftl_stream_create
21:25:19.068: 
21:25:19.072: All scene data cleared
21:25:19.072: ------------------------------------------------
21:25:19.092: WASAPI: Device 'Speakers / Headphones (Realtek Audio)' initialized
21:25:19.100: WASAPI: Device 'Microphone (Samson Meteor Mic)' initialized
21:25:19.187: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds
21:25:19.196: [Media Source 'Tribe logo Faded']: settings:
21:25:19.196: 	input:                   C:/Users/Myles/Downloads/Tribelogo 2_1.avi
21:25:19.196: 	input_format:            (null)
21:25:19.196: 	is_looping:              yes
21:25:19.196: 	is_forcing_scale:        yes
21:25:19.196: 	is_hw_decoding:          yes
21:25:19.196: 	is_clear_on_media_end:   yes
21:25:19.196: 	restart_on_activate:     yes
21:25:19.196: [Media Source 'Tribe Logo']: settings:
21:25:19.196: 	input:                   C:/Users/Myles/Downloads/Tribelogo 2_1.avi
21:25:19.196: 	input_format:            (null)
21:25:19.196: 	is_looping:              yes
21:25:19.196: 	is_forcing_scale:        yes
21:25:19.196: 	is_hw_decoding:          yes
21:25:19.196: 	is_clear_on_media_end:   yes
21:25:19.196: 	restart_on_activate:     yes
21:25:19.230: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.230: warning: Warning: data is not aligned! This can lead to a speedloss
21:25:19.248: ---------------------------------
21:25:19.248: [DShow Device: 'Face cam'] settings updated: 
21:25:19.248: 	video device: Logitech HD Pro Webcam C920
21:25:19.248: 	video path: \\?\usb#vid_046d&pid_082d&mi_00#6&1163de9e&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
21:25:19.248: 	resolution: 640x480
21:25:19.248: 	fps: 30.00 (interval: 333333)
21:25:19.248: 	format: I420
21:25:19.255: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.257: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.259: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.261: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.280: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.314: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.318: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.325: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.331: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.334: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.344: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.357: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.369: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.370: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.372: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.373: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.374: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.376: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.377: warning: deprecated pixel format used, make sure you did set range correctly
21:25:19.394: Switched to scene 'Chatting'
21:25:19.397: ------------------------------------------------
21:25:19.397: Loaded scenes:
21:25:19.397: - scene 'Main Stream':
21:25:19.397:     - source: 'Main Monitor' (monitor_capture)
21:25:19.397:     - source: 'Minecraft' (game_capture)
21:25:19.397:     - source: 'Music logo' (image_source)
21:25:19.397:     - source: 'Now Playing' (text_gdiplus)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'Firewatch' (game_capture)
21:25:19.397:     - source: 'Gifs' (window_capture)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Face cam' (dshow_input)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Lewts' (text_gdiplus)
21:25:19.397:     - source: 'Tribe logo Faded' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'StreamJAr' (browser_source)
21:25:19.397:     - source: 'Chat' (browser_source)
21:25:19.397:     - source: 'Loots' (browser_source)
21:25:19.397:     - source: 'Shoutout' (browser_source)
21:25:19.397: - scene 'BRB':
21:25:19.397:     - source: 'HOLD ON' (text_gdiplus)
21:25:19.397:     - source: 'Now Playing' (text_gdiplus)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'Music logo' (image_source)
21:25:19.397:     - source: 'Tribe Logo' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'StreamJAr' (browser_source)
21:25:19.397:     - source: 'BRB slide show' (slideshow)
21:25:19.397:     - source: 'Countdown' (text_gdiplus)
21:25:19.397:     - source: 'Gifs' (window_capture)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Lewts' (text_gdiplus)
21:25:19.397: - scene 'Chatting':
21:25:19.397:     - source: 'FIRES OF HELL' (image_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Music logo' (image_source)
21:25:19.397:     - source: 'Face cam' (dshow_input)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Tribe logo Faded' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Now Playing' (text_gdiplus)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'StreamJAr' (browser_source)
21:25:19.397:     - source: 'Chat' (browser_source)
21:25:19.397:     - source: 'Loots' (browser_source)
21:25:19.397:     - source: 'Gifs' (window_capture)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Lewts' (text_gdiplus)
21:25:19.397:     - source: 'Shoutout' (browser_source)
21:25:19.397: - scene 'Stream starting':
21:25:19.397:     - source: 'Logo' (image_source)
21:25:19.397:     - source: 'Tribe Logo' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'starting' (text_gdiplus)
21:25:19.397:     - source: 'Music logo' (image_source)
21:25:19.397:     - source: 'Now Playing' (text_gdiplus)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'Countdown' (text_gdiplus)
21:25:19.397:     - source: 'Tribe Logo' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397: - scene 'Recording OW':
21:25:19.397:     - source: 'OW' (game_capture)
21:25:19.397:     - source: 'Face cam' (dshow_input)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397: - scene 'RAID TIME':
21:25:19.397:     - source: 'FIRES OF HELL' (image_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Music logo' (image_source)
21:25:19.397:     - source: 'Raid Call!' (image_source)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'Face cam' (dshow_input)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Tribe logo Faded' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Now Playing' (text_gdiplus)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'StreamJAr' (browser_source)
21:25:19.397:     - source: 'Chat' (browser_source)
21:25:19.397:     - source: 'Loots' (browser_source)
21:25:19.397:     - source: 'Lewts' (text_gdiplus)
21:25:19.397:     - source: 'Gifs' (window_capture)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397: - scene 'Boozled!':
21:25:19.397:     - source: 'FIRES OF HELL' (image_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Music logo' (image_source)
21:25:19.397:     - source: 'Face cam' (dshow_input)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Tribe logo Faded' (ffmpeg_source)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Now Playing' (text_gdiplus)
21:25:19.397:         - filter: 'Scroll' (scroll_filter)
21:25:19.397:     - source: 'StreamJAr' (browser_source)
21:25:19.397:     - source: 'Chat' (browser_source)
21:25:19.397:     - source: 'Loots' (browser_source)
21:25:19.397:     - source: 'Gifs' (window_capture)
21:25:19.397:         - filter: 'Chroma Key' (chroma_key_filter)
21:25:19.397:     - source: 'Lewts' (text_gdiplus)
21:25:19.397:     - source: 'Shoutout' (browser_source)
21:25:19.397:     - source: 'Boozled' (image_source)
21:25:19.397:         - filter: 'Color Key' (color_key_filter)
21:25:19.397: ------------------------------------------------
21:25:25.468: [ftl stream: 'adv_stream'] ftl_stream_start
21:25:25.468: 
21:25:25.468: ---------------------------------
21:25:25.468: [x264 encoder: 'streaming_h264'] preset: fast
21:25:25.468: [x264 encoder: 'streaming_h264'] profile: baseline
21:25:25.468: [x264 encoder: 'streaming_h264'] tune: zerolatency
21:25:25.468: [x264 encoder: 'streaming_h264'] settings:
21:25:25.468: 	rate_control: CBR
21:25:25.468: 	bitrate:      3500
21:25:25.468: 	buffer size:  3500
21:25:25.468: 	crf:          0
21:25:25.468: 	fps_num:      30
21:25:25.468: 	fps_den:      1
21:25:25.468: 	width:        1280
21:25:25.468: 	height:       720
21:25:25.468: 	keyint:       90
21:25:25.468: 	vfr:          off
21:25:25.468: 
21:25:25.468: [x264 encoder: 'streaming_h264'] custom settings: scenecut=0
21:25:25.476: ---------------------------------
21:25:25.476: [FFmpeg opus encoder: 'Track1'] bitrate: 160, channels: 2
21:25:25.476: warning: No channel layout specified. Opus encoder will use Vorbis channel layout for 2 channels.
21:25:25.476: ftl-stream: connect thread
21:25:25.476: 
21:25:25.477: [ftl stream: 'adv_stream'] init_connect
21:25:25.477: 
21:25:25.477: H.264 opts scenecut=0
21:25:25.477: 
21:25:25.477: [ftl stream: 'adv_stream'] Connecting to FTL Ingest URL auto...
21:25:27.020: [ftl stream: 'adv_stream'] Connection to auto successful
21:25:31.148: [ftl stream: 'adv_stream'] Speed test completed: Peak kbps 3343, initial rtt 92, final rtt -1, 55.46 lost packets
21:25:31.148: 
21:25:31.149: [3] It took 105 ms to query all ingests
21:25:31.149: 
21:25:31.149: [3] ingest6.sea01.beam.pro at ip 173.192.148.161 had the shortest RTT of 91 ms
21:25:31.149: 
21:25:31.149: [3] Successfully connected to ingest.  Media will be sent to port 8131
21:25:31.149: 
21:25:31.149: [3] Socket created
21:25:31.149: 
21:25:31.149: [3] Sender report base ntp time set to 1090921693281 us
21:25:31.149: 
21:25:31.149: [3] Stream (97) base dts set to 0 
21:25:31.149: 
21:25:31.149: [1] Sent 3754296 bytes in 4001 ms; send packets 2674 lost 1483 packets; (first rtt: 0, last 2000). Estimated peak bitrate 3343 kbps
21:25:31.149: 
21:25:31.151: ==== Streaming Start ===============================================
21:25:31.326: [3] Audio is ready and we have the first iframe, starting stream. (dropped 0 frames)
21:25:31.326: 
21:25:31.326: [3] Stream (96) base dts set to 0 
21:25:31.326: 
21:25:32.023: Avg packet send per second 58.6, total nack requests 0
21:25:32.023: avg transmit delay 64ms (min: 3, max: 164), avg rtt 128ms (min: 89, max: 318)
21:25:32.023: Queue an average of 4.20 fps (475.8 kbps), sent an average of 4.00 fps (465.2 kbps), queue fullness 0, max frame size 67172
21:25:37.026: Avg packet send per second 236.1, total nack requests 0
21:25:37.026: avg transmit delay 171ms (min: 0, max: 399), avg rtt 96ms (min: 89, max: 130)
21:25:37.026: Queue an average of 17.09 fps (2035.1 kbps), sent an average of 15.89 fps (1901.1 kbps), queue fullness 7, max frame size 164784
21:25:42.027: Avg packet send per second 291.7, total nack requests 0
21:25:42.027: avg transmit delay 618ms (min: 359, max: 894), avg rtt 92ms (min: 89, max: 98)
21:25:42.027: Queue an average of 21.39 fps (2572.8 kbps), sent an average of 19.66 fps (2378.3 kbps), queue fullness 17, max frame size 165844
21:25:47.031: Avg packet send per second 320.1, total nack requests 0
21:25:47.031: avg transmit delay 1008ms (min: 827, max: 1223), avg rtt 92ms (min: 89, max: 117)
21:25:47.031: Queue an average of 23.54 fps (2837.8 kbps), sent an average of 21.74 fps (2617.8 kbps), queue fullness 26, max frame size 133960
21:25:52.033: Avg packet send per second 338.7, total nack requests 0
21:25:52.034: avg transmit delay 1350ms (min: 1146, max: 1608), avg rtt 93ms (min: 89, max: 119)
21:25:52.034: Queue an average of 24.79 fps (2945.2 kbps), sent an average of 23.07 fps (2761.6 kbps), queue fullness 27, max frame size 123896
21:25:52.565: adding 21 milliseconds of audio buffering, total audio buffering is now 42 milliseconds
21:25:57.032: Avg packet send per second 349.2, total nack requests 0
21:25:57.032: avg transmit delay 1523ms (min: 1361, max: 1730), avg rtt 92ms (min: 89, max: 107)
21:25:57.032: Queue an average of 25.66 fps (3059.4 kbps), sent an average of 23.99 fps (2857.1 kbps), queue fullness 36, max frame size 140706
21:26:02.037: Avg packet send per second 357.8, total nack requests 0
21:26:02.037: avg transmit delay 1905ms (min: 1658, max: 2147), avg rtt 94ms (min: 89, max: 147)
21:26:02.037: Queue an average of 26.30 fps (3131.7 kbps), sent an average of 24.56 fps (2925.3 kbps), queue fullness 41, max frame size 143107
