### ISSUE TITLE
cant install OBS Studio 18.0.1 & FTL 0.9.4

### ISSUE THREAD

**Issue by towe102** [mixer/obs-studio-ftl#81]
wen trying to install OBS Studio 18.0.1 & FTL 0.9.4 i get a error that i need to find OBS Studio 18.0.1 & FTL 0.9.2.msi

**Comment by QuinnDamerell** [comment]
Do you have the previous version installed?

**Comment by towe102** [comment]
yes i have 8.0.1 & FTL 0.9.2 installed

**Comment by Maximilian-Reuter** [comment]
If this is still an issue, see if you still have the msi file of OBS Studio 18.0.1 & FTL 0.9.2 . If you do, you can try right clicking it and choosing uninstall and see if that helps. If you don't have the msi file anymore then you can download it from here: https://mega.nz/#!ytZxWI4b!OHO4rR2nPb4E4dD34jU7fGJKPPo5sASO85_ergRhBGo
