### ISSUE TITLE
OBS 18.0.1_ftl 0.9.4

### ISSUE THREAD

**Issue by DasWarlock** [mixer/obs-studio-ftl#82]
Battle eye Blocking Game cap
23:50:13: Starting BattlEye Service...

23:50:16: Launching game...
23:50:43: Note: File blocks can be ignored if they don't cause problems with the game.
23:50:43: [INFO] Blocked loading of file: "E:\OBSFTL\data\obs-plugins\win-capture\graphics-hook64.dll".

**Comment by Maximilian-Reuter** [comment]
Please look through similar issues next time. The reason this happens is because the dll isn't cryptographically signed. The solution is, to copy the same file from the original obs into the OBS FTL installation.

**Comment by DasWarlock** [comment]
thank you ill make sure i look thru things before reporting
