### ISSUE TITLE
obs ftl and no webcam issues 

### ISSUE THREAD

**Issue by Iampanzer** [mixer/obs-studio-ftl#86]
Many streamers are having the same problem where obf ftl ONLY wont show the web cam. The cam works fine, in windows and including obs.. just NOT ftl. I have tried updating drivers, software. ive tried rolling back to like 7 diff versions of obs ftl and even tacyon. No go.. I have completely removed obs including reg files. 

It works find in everything but obf ftl i have no idea how to fix this spent the best part of the last 4 days trying to fix.

**Comment by capgames** [comment]
I had this same issue, and only happened when i manually installed the creators update for windows 10, i bought a new webcam and that did not work. I reinstalled windows 10 (with creators update) and everything is fine which leads me to to believe the creators update broke stuff. 

Windows version 1703  creators update

I have also reported this to Microsoft too. The creators update should be a concidered variable to causing this

**Comment by MrJkDavid** [comment]
I am to having issues with this, I want to stream but the webcam will show up (meaning it's plugged in) but nothing is being displayed where it is meant to show up.

**Comment by BreninLlwyd** [comment]
i have this exact same problem, with obs, obs ftl and tachyon, but works fine with xsplit :/

**Comment by Soulless512** [comment]
anyone know how the hell to fix this, i would love to be using ftl and not regular obs for my stream tonight

**Comment by Kassestral** [comment]
samew issue here

**Comment by JimmyMac3** [comment]
Try this it may fix the issue - 
1 - In OBS-FTL right click on your Web Cam Source and go to PROPERTIES
2 - Change the Resolution/FPS Type to Custom (Never leave any video capture device on Device Default. OBS sucks at figuring out the default resolution)
3 - Change the Resolution to 1280x720 or lower until your webcam preview appears
4 - Save the changes and restart OBS-FTL to make sure they stick
5 - If you need to go back into Webcam PROPERTIES and change the Resolution to your cam native resolution such as 1920x1080
6 - Don't ever change the Relolution/FPS type to Device Default

Hope this helps - Here is a screen shot of my settings - 
[https://i.gyazo.com/0cd1364356d58d2a08d293796a2ddbe2.png](url)

**Comment by BreninLlwyd** [comment]
wow thanks for such answers, tried them all, but what solved it for me was uninstalling avast.
any recommended free, antivirus software?

**Comment by Kassestral** [comment]
I found a tweet from OBS stating that a windows update was causing the issue where we cannot get our webcams to display, thus deleting avast and restarting your PC is a sure fix for this, I guess all we can do is wait for a new build of FTL to be released with the patch fix for the webcam issue :)

**Comment by Soulless512** [comment]
so what free antivirus would you suggest over avast, since now with it's latest update it is causing nothing but problems

**Comment by JimmyMac3** [comment]
Actually at the moment the best free AV in the testing that we have done at my work (I'm an IT Guy) is Win 10 Defender built into windows. That plus keep all your Windows updates up is the best free protection for now. Never thought I would say that but its true

**Comment by KSib** [comment]
@JimmyMac3 I looked at some tests and it seems Microsoft has indeed stepped their game up. I don't know if I'd call it the best as far as free protection goes, but as far as ease of use it's probably #1 since it's configured and enabled by default. It's leagues more competitive than their offerings on 7, 8, and 8.1.
