### ISSUE TITLE
Direct3d and OBS Studio FTL

### ISSUE THREAD

**Issue by deathstalker616** [mixer/obs-studio-ftl#87]
I seem to be having a problem connecting up to Direct3d based applications, for example DOSBox-Daum (regular works fine due to it being OpenGL) and Thief: The Dark Project. This issue only occurs in OBS Studio FTL, not standard OBS Studio, and installing a slightly older version did not fix the problem. I did not have this issue on my old computer, a 4790k Gigabyte 3 with 16GB RAM, but on switching to my newer 7700k Asus Formula IX with 64GB RAM I cannot seem to get it to function. I believe it has something to do with FTL based on the fact that standard OBS works perfectly fine. As they share the same folder/settings, the only thing I can infer is that it is a compatibility issue brought forth by FTL specifically.

Both have been on Windows 8.1. I can play OpenGL based titles fine. I have tried changing my drivers to an older version without success. I have tried both OpenGL and Direct3D as a renderer for OBS, neither did anything different. I have run various combinations of Administrator Mode to get the program to be detected, nothing changes. I have altered around various checkmarks. I can confirm it doesn't work with them all on, them all on defaults, or them all on beyond the anti-cheat compatibility hook. I should also mention I normally use the x64 version of the program, but the x32 version does not solve the issue.

https://gist.github.com/anonymous/587204e60e29655b0817f6f67e2e6090

**Comment by JimmyMac3** [comment]
Try this. First off make sure your running x64 OBS-FTL and running it as administrator.
If you haven't already installed the latest OBS-Studio from obsproject.com
Once installed you should have an OBS-STUDIO and an OBS-STUDIO-FTL folder in your PROGRAM FILES (x86) folder

Copy and REPLACE the obs-studio-ftl/data/obs-plugins/win-capture folder with the same folder at obs-studio/data/obs-plugins/win-capture

Not sure if it is true or not but the thought is the win-capture plugin in OBS-FTL is not a digitally signed and certified ms plugin and the OBS-STUDIO one of course is.

Hope that helps

**Comment by deathstalker616** [comment]
Thanks indeed! That fixed it :)
