### ISSUE TITLE
Mac builds no longer listed for OBS-FTL

### ISSUE THREAD

**Issue by jamesweech** [mixer/obs-studio-ftl#90]
Hi there,

Just went to download the latest version of OBS-studio-FTL and noticed that you are no longer listing mac builds, is there a reason for this or can we get them included again?

Trying to compile on my own Mac but getting issues about not having qt5widgets I am just trying to resolve. If someone can help with that I don't mind doing the builds and putting them here as needed

Thank You! :)

**Comment by mrdasi** [comment]
+1

**Comment by St0rmyy** [comment]
+1

**Comment by narcogen** [comment]
I have compiled the latest version, but I have been told that others who do not have the same versions of various libraries installed in the same places may have trouble using them.

You can give it a whirl below. This is 18.0.1 with FTL 0.9.4:

https://dl.orangedox.com/1NOky8MIML4AK89PLu

**Comment by jamesweech** [comment]
Thank You! I will give it a go shortly, I was drowning in library issues and having compiling, if you have a list of packages you installed (assuming you used brew) maybe we can compare?

**Comment by narcogen** [comment]
I wrote a post in the OBS subreddit and on the OBS Development forum when I started doing my own builds. It includes a step-by-step for how I did them, although some things (like installation of Qt) I had done long ago for other reasons. 

Most of the dependencies I install with Homebrew.

https://www.reddit.com/r/obs/comments/5yqb09/macos_builds_of_obs_18_and_obsftl_18/

**Comment by jamesweech** [comment]
Sorry @narcogen but won't launch

![screen shot 2017-05-17 at 20 13 38](https://cloud.githubusercontent.com/assets/2097695/26171581/5e3372f4-3b3d-11e7-9d01-89eaa487aac3.png)

**Comment by narcogen** [comment]
Yes, it seems to be sensitive to having certain libraries (Qt, ffmpeg) located in the same place and being the same versions as I have them in order to work. Putting a symlink on your system to link from where my binary expects it to be (in this case, /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib) or else using homebrew to install that version and then brew link it.

Or else you might try compiling with the instructions in the reddit post, and then see where that runs into problems.

**Comment by jamesweech** [comment]
I'm sorry but i'm running into silly issues still @narcogen Chances are to do with me being noobish with compiling on MacOS but even using your premade binaries. I've checked and the file location for /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib appears to be there and populated but I am still crashing with the following:

![screen shot 2017-07-11 at 10 12 18 pm](https://user-images.githubusercontent.com/2097695/28090934-03398ca2-6686-11e7-9d31-5de9e78ca60a.png)

Thanks for all your help with this! :)

**Comment by narcogen** [comment]
Is this error the same whether you compile yourself or use my binary?

Mine was built on 10.11. so there's a good chance my binary won't work on 10.12 anyway. I don't have a Sierra machine to test on.

I'm also just a noob when it comes to these things, but the error there seems to indicate that there's some other thing missing.

What version of Qt did you install, and how did you install it?

**Comment by jamesweech** [comment]
@QuinnDamerell-MS Why was this closed? We still don't have a mac build and I am working through @narcogen 's questions.

**Comment by QuinnDamerell-MS** [comment]
Sorry, I closed all of the issues because we are not integrated into official OBS. If you want to continue working, I can reopen it for you. 

You can find official mac builds of OBS (with FTL) here: https://obsproject.com/

**Comment by narcogen** [comment]
There is an official build of 20.0.1 with FTL support.
