### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by TarasDev** [mixer/obs-studio-ftl#94]
14:33:25.881: [ftl stream: 'simple_stream'] Connecting to FTL Ingest URL ingest-fra.mixer.com...
14:33:27.981: [ftl stream: 'simple_stream'] Ingest connect failed with: An Internal error occurred (6)
14:33:27.981: [ftl stream: 'simple_stream'] Connection to ingest-fra.mixer.com failed: -4

**Comment by sslivins** [comment]
Can you go here and paste what you get?  https://beam.pro/api/v1/ingests/best

**Comment by micky2171** [comment]
I'm having the same problems!
`[{"ip":"169.50.64.93","name":"ingest21.lon02.beam.pro"},{"ip":"169.50.64.95","name":"ingest24.lon02.beam.pro"},{"ip":"169.50.64.68","name":"ingest18.lon02.beam.pro"}]`

**Comment by TarasDev** [comment]
[{"ip":"159.122.70.33","name":"ingest5.fra02.beam.pro"},{"ip":"169.50.30.89","name":"ingest4.fra02.beam.pro"},{"ip":"159.122.70.4","name":"ingest1.fra02.beam.pro"}]

**Comment by sslivins** [comment]
and it does this every time or just sometimes?  what if you try to use auto?

**Comment by micky2171** [comment]
It happens almost all the time, there have been 2 random times where it started working but I can not replicate that again. 

I also get errors like this sometimes:
`17:13:12.838: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
17:13:12.842: [CoreAudio encoder]: Adding CoreAudio AAC encoder
17:13:12.845: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/ftl.dll' not found, loading of module failed
17:13:12.849: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
17:13:12.851: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
17:13:12.852: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
17:13:12.853: Failed to load 'en-US' text for module: 'obs-browser.dll'
`

**Comment by sslivins** [comment]
what is your channel name?

**Comment by micky2171** [comment]
MickyD
https://mixer.com/MickyD

**Comment by micky2171** [comment]
Tried auto, same issue

**Comment by sslivins** [comment]
k, im looking into it right now

**Comment by micky2171** [comment]
Thank You! 👍

**Comment by sslivins** [comment]
can you try again now?

**Comment by sslivins** [comment]
actually, hold on...its not going to work yet...one more sec

**Comment by micky2171** [comment]
it worked for a quick second and then broke again :/

**Comment by micky2171** [comment]
Any luck?

**Comment by sslivins** [comment]
yes, i found the problem and i'm rolling out a fix.  there are a few servers on frankfurt that have it now and others will be available shortly

**Comment by micky2171** [comment]
Thank You, I will try again in 5 minutes 👍

**Comment by micky2171** [comment]
IT WORKS!!! Thank you so much!
